services:
  - type: worker
    name: slayd-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
